config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  # ['help', 'about', 'contact'].each do |action|
  #   get "static_pages/#{action}", as: "#{action}"
  # end

  get '/signup', to: 'users#new'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'
  get '/admin', to: 'static_pages#admin'
  post '/images', to: 'images#create'

  resources :users

  resources :articles
  resources :carousels

  resources :pages
  get 'jianshu/handle_image'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @carousels = Carousel::all()
    catid = params[:catid] || '本会章程'
    @article = Article.find_by(title: catid)
  end

  def help
  end

  def about
  end

  def contact
  end

  def admin
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_carousels.html.erb
<link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.min.css">

<div class="carousel-container">
  <!-- Slider main container -->
  <div class="swiper-container">
    <!-- Additional required wrapper -->
    <div class="swiper-wrapper">
      <!-- Slides -->
      <% @carousels.each do |carousel| %>
        <% if carousel.src.attached? %>
          <div class="swiper-slide"><%= image_tag carousel.src, class: 'carousel-image' %></div>
        <% end %>
      <% end %>
    </div>
    <!-- If we need pagination -->
    <div class="swiper-pagination"></div>
  </div>
</div>

<script src="https://unpkg.com/swiper/js/swiper.min.js"></script>
<script>
    var mySwiper = new Swiper('.swiper-container', {
        // Optional parameters
        loop: true,

        // If we need pagination
        pagination: {
            el: '.swiper-pagination',
        },
    })
</script>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<h1>About</h1>
<p>
  The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a>, part of the
  <a href="https://www.learnenough.com/">Learn Enough</a> family of
  tutorials, is a
  <a href="https://www.railstutorial.org/book">book</a> and
  <a href="https://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="https://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample app for the tutorial.
</p>

app/views/static_pages/admin.html.erb
<%= link_to "轮播图管理", carousels_path, class: 'btn btn-info' %>
<%= link_to "文章管理", articles_path, class: 'btn btn-info' %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="https://www.railstutorial.org/help">Rails Tutorial Help page</a>.
  To get help on this sample app, see the
  <a href="https://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
    book</a>.
</p>

app/views/static_pages/home.html.erb
<%= render 'carousels' %>


<div class="articles-container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="col-md-3 col-xs-12">
        <div class="list-group">
          <%= link_to "本会章程", root_path, class: "list-group-item list-group-item-action " + is_active_url("本会章程") %>
          <% ['会长致辞', '团体荣誉', '关于我们'].each do |title| %>
            <%= link_to title, root_path + '?catid=' + title, class: "list-group-item list-group-item-action " + is_active_url(title) %>
          <% end %>
          <%= link_to '活动记录', pages_path + '?type=activity', class: "list-group-item list-group-item-action " %>
        </div>

        <div class="list-group">
          <button type="button" class="list-group-item list-group-item-action active">
            联系方式 SERVICE
          </button>
          <button type="button" class="list-group-item list-group-item-action">邮箱: <%= link_to "ajefparis@gmail.com", "mailto:ajefparis@gmail.com" %></button>
          <button type="button" class="list-group-item list-group-item-action">服务热线: <%= link_to "06.59.46.73.50", "tel:0659467350" %></button>
        </div>
      </div>

      <% unless @article.nil? %>
        <div class="col-md-9 col-xs-12">
          <h1 id="title"><%= @article.title %></h1>

          <p>
            <%= raw @article.rendered_content %>
          </p>

        </div>
      <% end %>
    </div>
  </div>
</div>