config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  # ['help', 'about', 'contact'].each do |action|
  #   get "static_pages/#{action}", as: "#{action}"
  # end

  get '/signup', to: 'users#new'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'
  get '/admin', to: 'static_pages#admin'
  post '/images', to: 'images#create'

  resources :users

  resources :articles
  resources :carousels

  resources :pages
  get 'jianshu/handle_image'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :raw_content, presence: true
  validates :level, presence: true

  before_save do
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, extensions = {})
    self.rendered_content = markdown.render(raw_content)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_login

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find_by(id: params[:id])
    if @article.nil?
      @article = Article.find_by(title: params[:id])
    end
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html {redirect_to @article, notice: 'Article was successfully created.'}
        format.json {render :show, status: :created, location: @article}
      else
        format.html {render :new}
        format.json {render json: @article.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @article = Article.find(params[:id])
    respond_to do |format|
      if @article.update(article_params)
        format.html {redirect_to @article, notice: 'Article was successfully updated.'}
        format.json {render :show, status: :ok, location: @article}
      else
        format.html {render :edit}
        format.json {render json: @article.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    respond_to do |format|
      format.html {redirect_to articles_url, notice: 'Article was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :raw_content, :rendered_content, :level)
    end

    def require_login
      unless log_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to login_path
      end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<link rel="stylesheet" media="screen" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-markdown/2.10.0/css/bootstrap-markdown.min.css">
<link rel="stylesheet" media="screen" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-markdown-editor/2.0.2/css/bootstrap-markdown-editor.css">

<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, '标题' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :raw_content, '内容' %>
    <%= form.text_area :raw_content, rows: 15, class: 'form-control', id: 'markdown-editor' %>
  </div>

  <div class="form-group">
    <%= form.label :level, '类型' %>
    <select name="article[level]" id="article_level">
      <% {new: '新闻', activity: '活动', page: '页面'}.each_pair do |key, value| %>
        <option value="<%= key %>" <%= article.level == key.to_s ? 'selected' : ''%>><%= value %></option>
      <% end %>
    </select>
  </div>

  <%= form.submit class: 'btn btn-info' %>
<% end %>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-markdown/2.10.0/js/bootstrap-markdown.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.6/ace.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-markdown-editor/2.0.2/js/bootstrap-markdown-editor.js"></script>

<script>
    $('#markdown-editor').markdownEditor({
        imageUpload: true, // Activate the option
        uploadPath: '/images', // Path of the server side script that receive the files
        afterAll: function () {
            msgs.default.show();
            msgs.loading.hide();
            msgs.err.hide();
        },
        uploadFinished: function (i, file, response, time) {
            $md.val($md.val() + "![" + file.name + "](http://photography.naturestocklibrary.com/orca-stock-photo.jpg)\n").trigger('change');
            // response is the data you got back from server in JSON format.
        }
    });
</script>

app/views/articles/edit.html.erb
<h1>编辑内容</h1>
<%= link_to '返回', articles_path, class: 'btn btn-default' %>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<h1>文章列表</h1>

<%= link_to '后退', admin_path, class: 'btn btn-default' %>
<%= link_to '创建新文章', new_article_path, class: 'btn btn-info' %>

<table class="table">
  <thead>
  <tr>
    <th scope="row">#</th>
    <th scope="row">标题</th>
    <th scope="row">类型</th>
    <th scope="row">发布时间</th>
    <th scope="row" colspan="3">操作</th>
  </tr>
  </thead>
  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <th scope="row"><%= article.id %></th>
      <td><%= link_to article.title, article_url(article) %></td>
      <td><%= get_type_text article.level %></td>
      <td><%= article.created_at %></td>
      <td><%= link_to '编辑', edit_article_path(article) %></td>
      <td><%= link_to '删除', article, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1>创建新文章</h1>

<%= render 'form', article: @article %>

<%= link_to '后退', articles_path %>

app/views/articles/show.html.erb
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

<h1><%= @article.title %></h1>

<p>
  <%= raw @article.rendered_content %>
</p>