config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  # ['help', 'about', 'contact'].each do |action|
  #   get "static_pages/#{action}", as: "#{action}"
  # end

  get '/signup', to: 'users#new'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'
  get '/admin', to: 'static_pages#admin'
  post '/images', to: 'images#create'

  resources :users

  resources :articles
  resources :carousels

  resources :pages
  get 'jianshu/handle_image'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/carousel.rb
class Carousel < ApplicationRecord
  has_one_attached :src
end

app/controllers/carousels_controller.rb
class CarouselsController < ApplicationController
  before_action :require_login
  before_action :set_carousel, only: [:show, :edit, :update, :destroy]

  # GET /carousels
  # GET /carousels.json
  def index
    @carousels = Carousel.all
  end

  # GET /carousels/1
  # GET /carousels/1.json
  def show
  end

  # GET /carousels/new
  def new
    @carousel = Carousel.new
  end

  # GET /carousels/1/edit
  def edit
    @carousel = Carousel.find_by(params[:id])
  end

  def create
    @carousel = Carousel.new(carousel_params)
    if @carousel.save
      @carousel.src.attach(carousel_params[:src])
      flash[:success] = '创建成功'
      redirect_to carousels_path
    else
      flash.now[:error] = '创建失败'
      render new
    end
  end

  # PATCH/PUT /carousels/1
  # PATCH/PUT /carousels/1.json
  def update
    if @carousel.update(carousel_params)
      @carousel.src.attach(carousel_params[:src])
      flash[:success] = '创建成功'
      redirect_to carousels_path
    else
      flash.now[:error] = '创建失败'
      render new
    end
  end

  # DELETE /carousels/1
  # DELETE /carousels/1.json
  def destroy
    @carousel.destroy
    respond_to do |format|
      format.html {redirect_to carousels_url, notice: 'Carousel was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_carousel
    @carousel = Carousel.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def carousel_params
    params.require(:carousel).permit(:title, :src, :url)
  end

  def require_login
    unless log_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to login_path
    end
  end
end

app/helpers/carousels_helper.rb
module CarouselsHelper
end

app/views/carousels/_form.html.erb
<%= form_with(model: carousel, local: true) do |form| %>
  <% if carousel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carousel.errors.count, "error") %> prohibited this carousel from being saved:</h2>

      <ul>
        <% carousel.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, "名字" %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :src, '图片' %>
    <% if carousel.src.attached? %>
      <div>
        <%= image_tag carousel.src, width: 300 %>
      </div>
    <% end %>
    <%= form.file_field :src, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :url, "链接" %>
    <%= form.text_field :url, class: 'form-control' %>
  </div>

  <%= form.submit '创建', class: 'btn btn-info' %>
<% end %>

app/views/carousels/edit.html.erb
<h1>编辑轮播图</h1>

<%= link_to '返回', carousels_path, class: "btn btn-default" %>

<%= render 'form', carousel: @carousel %>

app/views/carousels/index.html.erb
<h1>轮播图列表</h1>

<%= link_to '后退', admin_path, class: 'btn btn-default' %>
<%= link_to '创建轮播图', new_carousel_path, class: 'btn btn-info' %>

<table class="table">
  <thead>
  <tr>
    <th scope="row">#</th>
    <th scope="row">标题</th>
    <th scope="row">图片</th>
    <th scope="row" colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @carousels.each do |carousel| %>
    <tr>
      <td><%= carousel.title %></td>
      <% if carousel.src.attached? %>
        <td><%= image_tag carousel.src, width: 100 %></td>
      <% end %>

      <td><%= link_to '编辑', edit_carousel_path(carousel) %></td>
      <td><%= link_to '删除', carousel, method: :delete, data: {confirm: '确定要删除吗?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/carousels/new.html.erb
<%= link_to '后退', carousels_path, class: 'btn btn-default' %>

<h1>创建轮播图</h1>

<%= render 'form', carousel: @carousel %>

app/views/carousels/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @carousel.title %>
</p>

<p>
  <strong>Src:</strong>
  <%= @carousel.src %>
</p>

<p>
  <strong>Url:</strong>
  <%= @carousel.url %>
</p>

<%= link_to 'Edit', edit_carousel_path(@carousel) %> |
<%= link_to 'Back', carousels_path %>