config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  # ['help', 'about', 'contact'].each do |action|
  #   get "static_pages/#{action}", as: "#{action}"
  # end

  get '/signup', to: 'users#new'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'
  get '/admin', to: 'static_pages#admin'
  post '/images', to: 'images#create'

  resources :users

  resources :articles
  resources :carousels

  resources :pages
  get 'jianshu/handle_image'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="col-md-12 col-sm-12">
      <div class="footer-primary-links">
        <div class="col-md-4 col-xs-6">
          <ul>
            <li>
              电话: <%= link_to "06.59.46.73.50", "tel:0659467350" %>
            </li>
            <li>
              邮箱: <%= link_to "ajefparis@gmail.com", "mailto:ajefparis@gmail.com" %>
            </li>
          </ul>
        </div>
        <div class="col-md-4 col-xs-6">
          <div class="row">
            <div class="col-md-6">
              <ul>
                <li>
                  <%= link_to "网站首页", root_path %>
                </li>
                <li>
                  <%= link_to "活动记录", pages_path + '?type=activity' %>
                </li>
                <li>
                  <%= link_to "入会须知", page_path('入会须知') %>
                </li>
              </ul>
            </div>
            <div class="col-md-6">
              <ul>
                <li>
                  <%= link_to "关于我们", page_path('关于我们')  %>
                </li>
                <li>
                  <%= link_to "会员风采", page_path('会员服务') %>
                </li>
                <li>
                  <%= link_to "公益事业", page_path('公益事业') %>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-xs-12">
          <%= image_tag 'qr.png', width: 50 %>
          <div>入会申请</div>
        </div>
      </div>
    </div>
  </div>
  <div class="copyright">
    <!--    Copyright © 2018 欧洲青年技术家协会 版权所有-->
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="container-fluid header">
  <div class="container">
    <header class="navbar">
      <div>
        <%= link_to(image_tag("logo.png", width: 60, class: 'logo'), root_path, id: "logo") %>
        <nav>
          <ul class="nav navbar-nav">
            <li><%= link_to "网站首页", root_path %></li>
            <li><%= link_to "入会须知", page_path('入会须知') %></li>
            <li><%= link_to "活动记录", pages_path + '?type=activity' %></li>
            <li><%= link_to "公益事业", page_path('公益事业') %></li>
            <li><%= link_to "会员服务", page_path('会员服务') %></li>

            <% if log_in? %>
              <li><%= link_to "后台", admin_path %></li>
              <li><%= link_to "退出登录", logout_path, method: :delete %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render "layouts/shim" %>
</head>

<body>

<%= render 'layouts/header' %>
<div class="container">
  <div class="main-container">
    <%= render 'shared/flush' %>
    <%= yield %>
  </div>
</div>

<%= render 'layouts/footer' %>
</body>
</html>